
// your SQL details. MYSQL_BASE is the database name.
#define MYSQL_HOST		""
#define MYSQL_BASE		""
#define MYSQL_PASS		""
#define MYSQL_USER		""
 

 
// the maxplayers on your server - you don't need to change this value
const MAX_PLAYERS		= 32

// the minimum amount of players required on the server for the system to work. Less players will cause achievements not being won or progressed on.
const MIN_PLAYERS		= 5

// if you're going to use more 128 achievements, increase this value
const MAX_ACHIEVEMENTS		= 128
 

 // name of the sound played when an achievement is won. If you don't want the sound, comment the line (put // in front of it).
#define ACHIEVEMENT_SOUND	"achievement_unlocked.wav"
